name: SurvivalGames
api: [2.0.0, 2.1.0]
version: 1.0.9
main: Andre\SurvivalGames\Main
load: POSTWORLD
author: AndreTheGamer
website: https://github.com/xZeroMCPE/SurvivalGames


commands:
 sg:
  permission: SurvivalGamess.command.sg
  description: SurvivalGamess Main Command
  usage: §d§oUse §e/sg help
 lobby:
  permission: SurvivalGames.command.lobby
  description: back to lobby
  usage: /lobby
permissions:
 SurvivalGamess.*:
  description: the main permission
  default: op
  children:
   SurvivalGamess.command.*:
    description: use commands in plugin
    default: op
    children:
     SurvivalGamess.command.lobby:
      description: back to lobby
      default: true
     SurvivalGamess.command.sg:
      description: set SurvivalGamess
      default: op
   sg.touch.startgame:
    description: click the sign and join the game
    default: true
   SurvivalGamess.vip:
    description: Kit for vips
    default: op
